//go:build linux

package telegramcommands

import (
	"github.com/idolum-ai/aphelion/core"
	"github.com/idolum-ai/aphelion/session"
	"time"
)

type stubCommandRouter struct {
	status                            core.SessionStatus
	statusChat                        core.ChatStatusSnapshot
	statusSystem                      core.SystemStatusSnapshot
	autonomyStatus                    core.AutonomyStatusSnapshot
	statusDurables                    core.DurableAgentsStatusSnapshot
	statusReadableSummary             string
	tailnetStatus                     core.TailnetStatusSnapshot
	tailnetStatusErr                  error
	tailnetStatusSenderID             int64
	tailnetSurfaces                   []core.TailnetSurfaceStatus
	tailnetSurfacesErr                error
	tailnetSurfacesSenderID           int64
	tailnetGrantBindings              []core.TailnetGrantBindingStatus
	tailnetGrantBindingsErr           error
	tailnetGrantBindingsSenderID      int64
	latestDoctorReport                session.DoctorReportRecord
	latestDoctorReportOK              bool
	latestDoctorReportErr             error
	latestDoctorReportChatID          int64
	latestDoctorReportSenderID        int64
	revokeTailnetSurfaceSenderID      int64
	revokeTailnetSurfaceID            string
	revokeTailnetSurfaceReason        string
	revokeTailnetSurfaceReturn        core.TailnetSurfaceStatus
	revokeTailnetSurfaceOK            bool
	revokeTailnetSurfaceErr           error
	statusChatErr                     error
	statusMessage                     *core.InboundMessage
	statusMessageSnapshot             core.ChatStatusSnapshot
	statusSystemErr                   error
	autonomyStatusErr                 error
	statusDurablesErr                 error
	stop                              core.StopResult
	stopInput                         int64
	stopCalls                         int
	stopMessage                       *core.InboundMessage
	stopMessageResult                 core.StopResult
	streamControls                    map[string]int64
	streamStopID                      string
	streamStopChatID                  int64
	streamStopCalls                   int
	newResult                         core.NewSessionResult
	newErr                            error
	newChatID                         int64
	newSenderID                       int64
	newMessage                        *core.InboundMessage
	newMessageResult                  core.NewSessionResult
	detach                            core.DetachResult
	detachErr                         error
	detachChatID                      int64
	detachSenderID                    int64
	detachMessage                     *core.InboundMessage
	detachMessageResult               core.DetachResult
	personaEffort                     string
	governorEffort                    string
	canRestart                        bool
	modelStatuses                     []core.ModelSlotStatus
	modelStatusesErr                  error
	validateModelSlotInput            core.ModelSlotConfig
	validateModelSlotReturn           core.ModelValidation
	setModelSlotInput                 core.ModelSlotConfig
	setModelSlotActor                 string
	setModelSlotReason                string
	setModelSlotReturn                core.ModelSlotStatus
	setModelSlotErr                   error
	clearModelSlotInput               string
	clearModelSlotActor               string
	clearModelSlotReason              string
	clearModelSlotReturn              core.ModelSlotStatus
	clearModelSlotErr                 error
	modelSlotHistoryInput             string
	modelSlotHistoryLimit             int
	modelSlotHistoryReturn            []session.ModelSlotOverrideRecord
	modelSlotHistoryErr               error
	continuationState                 session.ContinuationState
	continuationStateInput            int64
	continuationStateMessage          core.InboundMessage
	continuationStateErr              error
	approveContinuationInput          int64
	approveContinuationMessage        core.InboundMessage
	approveContinuationApprover       int64
	approveContinuationPhaseIDs       []string
	approveContinuationReturn         session.ContinuationState
	approveContinuationErr            error
	stopContinuationInput             int64
	stopContinuationMessage           core.InboundMessage
	stopContinuationResult            core.StopResult
	stopContinuationErr               error
	triggerContinuationInput          int64
	triggerContinuationMessage        core.InboundMessage
	triggerContinuationErr            error
	triggerContinuationStarted        chan struct{}
	triggerContinuationRelease        <-chan struct{}
	callbackErrorRecords              []stubCallbackErrorRecord
	refreshContinuationInput          int64
	refreshContinuationMessage        core.InboundMessage
	refreshContinuationReason         string
	refreshContinuationReturn         session.ContinuationState
	refreshContinuationSent           bool
	refreshContinuationErr            error
	restartInput                      int64
	restartCalls                      int
	queuedReinstallMsg                *core.InboundMessage
	queuedDoctorMsg                   *core.InboundMessage
	queueDoctorErr                    error
	autoApproveChatID                 int64
	autoApproveSenderID               int64
	autoApproveArgs                   string
	autoApproveMessage                *core.InboundMessage
	autoApproveStatusChatID           int64
	autoApproveStatusSenderID         int64
	autoApproveStatusMessage          *core.InboundMessage
	autoApproveStatusReturn           string
	autoApproveStatusErr              error
	autoApproveReturn                 string
	autoApproveErr                    error
	approvalWindowAction              string
	approvalWindowCancelCalls         int
	approvalWindowOfferID             string
	approvalWindowSenderID            int64
	approvalWindowOfferSource         string
	approvalWindowMessage             *core.InboundMessage
	approvalWindowDuration            time.Duration
	defaultApprovalWindowDuration     time.Duration
	suppressPostApprovalDefaultWindow bool
	suppressPostApprovalErr           error
	suppressPostApprovalSource        string
	suppressPostApprovalMessage       *core.InboundMessage
	approvalWindowReturn              string
	approvalWindowActive              bool
	approvalWindowCanceled            bool
	approvalWindowReturnBeforeResolve bool
	approvalWindowErr                 error
	approvalWindowLookupOffer         session.ApprovalWindowOffer
	approvalWindowLookupOK            bool
	approvalWindowLookupErr           error
	resolvedDecisionID                string
	resolvedDecisionChoice            string
	resolvedDecisionActor             int64
	resolvedDecisionOK                bool
	resolvedDecisionPeekOK            bool
	autonomyChatID                    int64
	autonomySenderID                  int64
	autonomyArgs                      string
	autonomyMessage                   *core.InboundMessage
	autonomyStatusMessage             *core.InboundMessage
	autonomyReturn                    string
	autonomyErr                       error
	toggleProgressChatID              int64
	toggleProgressSenderID            int64
	toggleProgressRunID               int64
	toggleProgressDetails             bool
	toggleProgressUpdated             bool
	toggleProgressText                string
	toggleProgressErr                 error
	durableWizardChatID               int64
	durableWizardSenderID             int64
	durableWizardAction               string
	durableWizardAgentID              string
	durableWizardAnswers              map[string]any
	durableWizardResult               string
	durableWizardErr                  error
	durableAgentsList                 []core.DurableAgentStatusSnapshot
	durableAgentsListErr              error
	durableAgentsListSenderID         int64
	startDurableChatID                int64
	startDurableSenderID              int64
	startDurableAgentID               string
	startDurableMessage               string
	startDurableResult                string
	startDurableErr                   error
	durableLifecycleChatID            int64
	durableLifecycleSenderID          int64
	durableLifecycleAgentID           string
	durableLifecycleAction            string
	durableLifecycleResult            string
	durableLifecycleErr               error
	agentAnalyzeMsg                   *core.InboundMessage
	agentAnalyzeResult                string
	agentAnalyzeErr                   error
	agentCallbackChatID               int64
	agentCallbackAgentID              string
	agentCallbackMessageID            int64
	agentCallbackSurface              string
	agentCallbackErr                  error
	agentReplyChatID                  int64
	agentReplyMessageID               int64
	agentReplyAgentID                 string
	agentReplyOK                      bool
	agentReplyErr                     error
	missionCommandText                string
	missionCommandErr                 error
	missionCommandChatID              int64
	missionCommandSenderID            int64
	missionCommandArgs                string
	missionHomeMissions               []session.MissionState
	missionHomeWorking                session.WorkingObjective
	missionHomeIsAdmin                bool
	missionHomeErr                    error
	missionHomeChatID                 int64
	missionHomeSenderID               int64
	missionDetailsMission             session.MissionState
	missionDetailsEvents              []session.MissionEvent
	missionDetailsErr                 error
	missionDetailsChatID              int64
	missionDetailsSenderID            int64
	missionDetailsID                  string
	setMissionPinnedMission           session.MissionState
	setMissionPinnedErr               error
	setMissionPinnedChatID            int64
	setMissionPinnedSenderID          int64
	setMissionPinnedID                string
	setMissionPinnedValue             bool
	updateMissionStatusMission        session.MissionState
	updateMissionStatusErr            error
	updateMissionStatusChatID         int64
	updateMissionStatusSenderID       int64
	updateMissionStatusID             string
	updateMissionStatusValue          session.MissionStatus
	missionLedgerHealth               session.MissionLedgerHealth
	missionLedgerHealthErr            error
	missionLedgerHealthSenderID       int64
	missionActionProposal             session.ActionProposal
	missionActionProposalErr          error
	missionActionProposalChatID       int64
	missionActionProposalSender       int64
	missionActionProposalID           string
	applyMissionProposalMission       session.MissionState
	applyMissionProposalChanged       bool
	applyMissionProposalErr           error
	applyMissionProposalChatID        int64
	applyMissionProposalSender        int64
	applyMissionProposalID            string
	applyMissionProposalChoice        string
	missionAskPrompt                  session.MissionAskPrompt
	missionAskPromptOK                bool
	missionAskPromptErr               error
	missionAskPromptSenderID          int64
	missionAskPromptID                string
	resolveMissionAskStatus           session.MissionAskStatus
	resolveMissionAskSummary          string
	resolveMissionAskErr              error
	queueMissionClarificationMsg      *core.InboundMessage
	queueMissionClarificationID       string
	queueMissionClarificationErr      error
	reentryRecommendation             session.ReentryRecommendation
	reentryRecommendationOK           bool
	reentryRecommendationErr          error
	reentryRecommendationSenderID     int64
	reentryRecommendationID           string
	ignoreReentryRecommendationErr    error
	ignoreReentryRecommendationID     string
	ignoreReentryRecommendationSender int64
	queueReentryRecommendationMsg     *core.InboundMessage
	queueReentryRecommendationID      string
	queueReentryCandidateID           string
	queueReentryRecommendationReturn  session.ReentryRecommendation
	queueReentryCandidateReturn       session.ReentryRecommendationCandidate
	queueReentrySelected              bool
	queueReentryErr                   error
	memoryReviewBySource              map[memoryReviewSource]memoryReviewSnapshot
	memoryReviewErr                   error
	memoryReviewChatID                int64
	memoryReviewSenderID              int64
	memoryReviewSource                memoryReviewSource
	memoryReviewMessage               core.InboundMessage
	threadCreateMsg                   *core.InboundMessage
	threadCreateReturn                session.TelegramThread
	threadCreateErr                   error
	threadGuideChatID                 int64
	threadGuideID                     int64
	threadGuideMessageID              int64
	threadReminderChatID              int64
	threadReminderID                  int64
	threadReminderMessageID           int64
	threadReminderSummary             string
	threadReminderSummaryKind         string
	threadReminderSenderID            int64
	threadReminderErr                 error
	ignoreReminderChatID              int64
	ignoreReminderSenderID            int64
	ignoreReminderThreadID            int64
	ignoreReminderMessageID           int64
	ignoreReminderReturn              string
	ignoreReminderErr                 error
	absorbReminderChatID              int64
	absorbReminderSenderID            int64
	absorbReminderThreadID            int64
	absorbReminderMessageID           int64
	absorbReminderReturn              string
	absorbReminderErr                 error
	threadCallbackChatID              int64
	threadCallbackID                  int64
	threadCallbackMessageID           int64
	threadCallbackSurface             string
	threadCallbackErr                 error
	threadCallbackClearChatID         int64
	threadCallbackClearMessageID      int64
	threadCallbackClearSurface        string
	threadCallbackClearErr            error
	callbackRetireChatID              int64
	callbackRetireMessageID           int64
	callbackRetireSurface             string
	callbackRetireErr                 error
	threadStartMsg                    *core.InboundMessage
	threadStartText                   string
	threadStartReturn                 session.TelegramThread
	threadStartErr                    error
	threadRouteMsg                    *core.InboundMessage
	threadRouteID                     int64
	threadRouteText                   string
	threadRouteReturn                 session.TelegramThread
	threadRouteErr                    error
	threadReplyChatID                 int64
	threadReplyMessageID              int64
	threadReplyReturn                 session.TelegramThread
	threadReplyOK                     bool
	threadReplyErr                    error
	threadRemindersReturn             []session.TelegramThreadReminder
	threadRemindersErr                error
	threadRemindersChatID             int64
	threadRemindersStatus             session.TelegramThreadReminderStatus
	threadRemindersLimit              int
	threadsReturn                     []session.TelegramThread
	threadsErr                        error
	threadsChatID                     int64
	threadSummaryMsg                  *core.InboundMessage
	threadSummaryReturn               string
	threadSummaryErr                  error
	mediaPickerRecordChatID           int64
	mediaPickerRecordMessageID        int64
	mediaPickerRecordInbound          core.InboundMessage
	mediaPickerRecordErr              error
	mediaPickerReturn                 core.InboundMessage
	mediaPickerOK                     bool
	mediaPickerErr                    error
	mediaPickerGetChatID              int64
	mediaPickerGetMessageID           int64
	mediaPickerMarkChatID             int64
	mediaPickerMarkMessageID          int64
	mediaPickerMarkErr                error
	routeAcceptedMsg                  *core.InboundMessage
	routeAcceptedErr                  error
	promoteThreadChatID               int64
	promoteThreadSenderID             int64
	promoteThreadID                   int64
	promoteThreadReturn               session.TelegramThreadPromotionResult
	promoteThreadErr                  error
	preparePromotionChatID            int64
	preparePromotionSenderID          int64
	preparePromotionHandoffID         string
	preparePromotionReturn            session.TelegramThreadPromotionResult
	preparePromotionErr               error
	cancelPromotionChatID             int64
	cancelPromotionSenderID           int64
	cancelPromotionHandoffID          string
	cancelPromotionReturn             session.TelegramThreadPromotionResult
	cancelPromotionErr                error
	supersedePromotionChatID          int64
	supersedePromotionSenderID        int64
	supersedePromotionHandoffID       string
	supersedePromotionReturn          session.TelegramThreadPromotionResult
	supersedePromotionErr             error
	absorbThreadChatID                int64
	absorbThreadSenderID              int64
	absorbThreadID                    int64
	absorbThreadReturn                string
	absorbThreadErr                   error
	clarificationMsg                  *core.InboundMessage
	order                             *[]string
}
