//go:build linux

package telegramcommands

import (
	"github.com/idolum-ai/aphelion/core"
	"github.com/idolum-ai/aphelion/session"
	"time"
)

type stubCommandRouter struct {
	status                       core.SessionStatus
	statusChat                   core.ChatStatusSnapshot
	statusSystem                 core.SystemStatusSnapshot
	autonomyStatus               core.AutonomyStatusSnapshot
	statusDurables               core.DurableAgentsStatusSnapshot
	statusReadableSummary        string
	tailnetStatus                core.TailnetStatusSnapshot
	tailnetStatusErr             error
	tailnetStatusSenderID        int64
	tailnetSurfaces              []core.TailnetSurfaceStatus
	tailnetSurfacesErr           error
	tailnetSurfacesSenderID      int64
	tailnetGrantBindings         []core.TailnetGrantBindingStatus
	tailnetGrantBindingsErr      error
	tailnetGrantBindingsSenderID int64
	latestDoctorReport           session.DoctorReportRecord
	latestDoctorReportOK         bool
	latestDoctorReportErr        error
	latestDoctorReportChatID     int64
	latestDoctorReportSenderID   int64
	revokeTailnetSurfaceSenderID int64
	revokeTailnetSurfaceID       string
	revokeTailnetSurfaceReason   string
	revokeTailnetSurfaceReturn   core.TailnetSurfaceStatus
	revokeTailnetSurfaceOK       bool
	revokeTailnetSurfaceErr      error
	statusChatErr                error
	statusMessage                *core.InboundMessage
	statusMessageSnapshot        core.ChatStatusSnapshot
	statusSystemErr              error
	autonomyStatusErr            error
	statusDurablesErr            error
	stop                         core.StopResult
	stopInput                    int64
	stopCalls                    int
	stopMessage                  *core.InboundMessage
	stopMessageResult            core.StopResult
	streamControls               map[string]int64
	streamStopID                 string
	streamStopChatID             int64
	streamStopCalls              int
	newResult                    core.NewSessionResult
	newErr                       error
	newChatID                    int64
	newSenderID                  int64
	newMessage                   *core.InboundMessage
	newMessageResult             core.NewSessionResult
	detach                       core.DetachResult
	detachErr                    error
	detachChatID                 int64
	detachSenderID               int64
	detachMessage                *core.InboundMessage
	detachMessageResult          core.DetachResult
	personaEffort                string
	governorEffort               string
	canRestart                   bool
	modelStatuses                []core.ModelSlotStatus
	modelStatusesErr             error
	validateModelSlotInput       core.ModelSlotConfig
	validateModelSlotReturn      core.ModelValidation
	setModelSlotInput            core.ModelSlotConfig
	setModelSlotActor            string
	setModelSlotReason           string
	setModelSlotTTL              time.Duration
	setModelSlotReturn           core.ModelSlotStatus
	setModelSlotErr              error
	rollbackModelSlotInput       string
	rollbackModelSlotActor       string
	rollbackModelSlotReason      string
	rollbackModelSlotReturn      core.ModelSlotStatus
	rollbackModelSlotErr         error
	clearModelSlotInput          string
	clearModelSlotActor          string
	clearModelSlotReason         string
	clearModelSlotReturn         core.ModelSlotStatus
	clearModelSlotErr            error
	modelSlotHistoryInput        string
	modelSlotHistoryLimit        int
	modelSlotHistoryReturn       []session.ModelSlotOverrideRecord
	modelSlotHistoryErr          error
	continuationState            session.ContinuationState
	continuationStateInput       int64
	continuationStateMessage     core.InboundMessage
	continuationStateErr         error
	approveContinuationInput     int64
	approveContinuationMessage   core.InboundMessage
	approveContinuationApprover  int64
	approveContinuationReturn    session.ContinuationState
	approveContinuationErr       error
	stopContinuationInput        int64
	stopContinuationMessage      core.InboundMessage
	stopContinuationResult       core.StopResult
	stopContinuationErr          error
	triggerContinuationInput     int64
	triggerContinuationMessage   core.InboundMessage
	triggerContinuationErr       error
	triggerContinuationStarted   chan struct{}
	triggerContinuationRelease   <-chan struct{}
	callbackErrorRecords         []stubCallbackErrorRecord
	refreshContinuationInput     int64
	refreshContinuationMessage   core.InboundMessage
	refreshContinuationReason    string
	refreshContinuationReturn    session.ContinuationState
	refreshContinuationSent      bool
	refreshContinuationErr       error
	restartInput                 int64
	restartCalls                 int
	queuedReinstallMsg           *core.InboundMessage
	queuedDoctorMsg              *core.InboundMessage
	queueDoctorErr               error
	autoApproveChatID            int64
	autoApproveSenderID          int64
	autoApproveArgs              string
	autoApproveMessage           *core.InboundMessage
	autoApproveStatusChatID      int64
	autoApproveStatusSenderID    int64
	autoApproveStatusMessage     *core.InboundMessage
	autoApproveStatusReturn      string
	autoApproveStatusErr         error
	autoApproveReturn            string
	autoApproveErr               error
	approvalWindowAction         string
	approvalWindowOfferID        string
	approvalWindowOfferSource    string
	approvalWindowMessage        *core.InboundMessage
	approvalWindowDuration       time.Duration
	approvalWindowReturn         string
	approvalWindowErr            error
	autonomyChatID               int64
	autonomySenderID             int64
	autonomyArgs                 string
	autonomyMessage              *core.InboundMessage
	autonomyStatusMessage        *core.InboundMessage
	autonomyReturn               string
	autonomyErr                  error
	toggleProgressChatID         int64
	toggleProgressSenderID       int64
	toggleProgressRunID          int64
	toggleProgressDetails        bool
	toggleProgressUpdated        bool
	toggleProgressText           string
	toggleProgressErr            error
	durableWizardChatID          int64
	durableWizardSenderID        int64
	durableWizardAction          string
	durableWizardAgentID         string
	durableWizardAnswers         map[string]any
	durableWizardResult          string
	durableWizardErr             error
	durableAgentsList            []core.DurableAgentStatusSnapshot
	durableAgentsListErr         error
	durableAgentsListSenderID    int64
	startDurableChatID           int64
	startDurableSenderID         int64
	startDurableAgentID          string
	startDurableResult           string
	startDurableErr              error
	missionCommandText           string
	missionCommandErr            error
	missionCommandChatID         int64
	missionCommandSenderID       int64
	missionCommandArgs           string
	missionHomeMissions          []session.MissionState
	missionHomeWorking           session.WorkingObjective
	missionHomeIsAdmin           bool
	missionHomeErr               error
	missionHomeChatID            int64
	missionHomeSenderID          int64
	missionDetailsMission        session.MissionState
	missionDetailsEvents         []session.MissionEvent
	missionDetailsErr            error
	missionDetailsChatID         int64
	missionDetailsSenderID       int64
	missionDetailsID             string
	setMissionPinnedMission      session.MissionState
	setMissionPinnedErr          error
	setMissionPinnedChatID       int64
	setMissionPinnedSenderID     int64
	setMissionPinnedID           string
	setMissionPinnedValue        bool
	updateMissionStatusMission   session.MissionState
	updateMissionStatusErr       error
	updateMissionStatusChatID    int64
	updateMissionStatusSenderID  int64
	updateMissionStatusID        string
	updateMissionStatusValue     session.MissionStatus
	missionLedgerHealth          session.MissionLedgerHealth
	missionLedgerHealthErr       error
	missionLedgerHealthSenderID  int64
	missionActionProposal        session.ActionProposal
	missionActionProposalErr     error
	missionActionProposalChatID  int64
	missionActionProposalSender  int64
	missionActionProposalID      string
	applyMissionProposalMission  session.MissionState
	applyMissionProposalChanged  bool
	applyMissionProposalErr      error
	applyMissionProposalChatID   int64
	applyMissionProposalSender   int64
	applyMissionProposalID       string
	applyMissionProposalChoice   string
	memoryReviewBySource         map[memoryReviewSource]memoryReviewSnapshot
	memoryReviewErr              error
	memoryReviewChatID           int64
	memoryReviewSenderID         int64
	memoryReviewSource           memoryReviewSource
	memoryReviewMessage          core.InboundMessage
	memoryFocusByChat            map[int64]core.MemoryFocus
	memoryFocusByThread          map[int64]core.MemoryFocus
	setMemoryFocusMessage        core.InboundMessage
	clearMemoryFocusMessage      core.InboundMessage
	clearMemoryFocusChatID       int64
	clearMemoryFocusResult       bool
	threadCreateMsg              *core.InboundMessage
	threadCreateReturn           session.TelegramThread
	threadCreateErr              error
	threadGuideChatID            int64
	threadGuideID                int64
	threadGuideMessageID         int64
	threadCallbackChatID         int64
	threadCallbackID             int64
	threadCallbackMessageID      int64
	threadCallbackSurface        string
	threadCallbackErr            error
	threadStartMsg               *core.InboundMessage
	threadStartText              string
	threadStartReturn            session.TelegramThread
	threadStartErr               error
	threadRouteMsg               *core.InboundMessage
	threadRouteID                int64
	threadRouteText              string
	threadRouteReturn            session.TelegramThread
	threadRouteErr               error
	threadReplyChatID            int64
	threadReplyMessageID         int64
	threadReplyReturn            session.TelegramThread
	threadReplyOK                bool
	threadReplyErr               error
	threadsReturn                []session.TelegramThread
	threadsErr                   error
	threadsChatID                int64
	threadSummaryMsg             *core.InboundMessage
	threadSummaryReturn          string
	threadSummaryErr             error
	absorbThreadChatID           int64
	absorbThreadSenderID         int64
	absorbThreadID               int64
	absorbThreadReturn           string
	absorbThreadErr              error
	order                        *[]string
}
